export const CHARACTER_SHEET_LIST_READ = 'CHARACTER_SHEET_LIST_READ';
export const CHARACTER_SHEET_LIST_READ_PENDING = 'CHARACTER_SHEET_LIST_READ_PENDING';
export const CHARACTER_SHEET_LIST_READ_SUCCESS = 'CHARACTER_SHEET_LIST_READ_SUCCESS';
export const CHARACTER_SHEET_LIST_READ_FAILED = 'CHARACTER_SHEET_LIST_READ_FAILED';

export const CHARACTER_SHEET_DELETE = 'CHARACTER_SHEET_DELETE';
export const CHARACTER_SHEET_DELETE_PENDING = 'CHARACTER_SHEET_DELETE_PENDING';
export const CHARACTER_SHEET_DELETE_SUCCESS = 'CHARACTER_SHEET_DELETE_SUCCESS';
export const CHARACTER_SHEET_DELETE_FAILED = 'CHARACTER_SHEET_DELETE_FAILED';

export const CHARACTER_SHEET_LIST_CLEAR = 'CHARACTER_SHEET_LIST_CLEAR';