export const CHARACTER_SHEET_LIST_READ: string = 'CHARACTER_SHEET_LIST_READ';
export const CHARACTER_SHEET_LIST_READ_PENDING: string = 'CHARACTER_SHEET_LIST_READ_PENDING';
export const CHARACTER_SHEET_LIST_READ_SUCCESS: string = 'CHARACTER_SHEET_LIST_READ_SUCCESS';
export const CHARACTER_SHEET_LIST_READ_FAILED: string = 'CHARACTER_SHEET_LIST_READ_FAILED';
export const CHARACTER_SHEET_LIST_CLEAR: string = 'CHARACTER_SHEET_LIST_CLEAR';