export const CHARACTER_SHEET_NAME_UPDATE = 'CHARACTER_SHEET_NAME_UPDATE';
export const CHARACTER_SHEET_PLAYER_UPDATE = 'CHARACTER_SHEET_PLAYER_UPDATE';

export const CHARACTER_SHEET_CREATE = 'CHARACTER_SHEET_CREATE';
export const CHARACTER_SHEET_CREATE_PENDING = 'CHARACTER_SHEET_CREATE_PENDING';
export const CHARACTER_SHEET_CREATE_SUCCESS = 'CHARACTER_SHEET_CREATE_SUCCESS';
export const CHARACTER_SHEET_CREATE_FAILED = 'CHARACTER_SHEET_CREATE_FAILED';

export const CHARACTER_SHEET_UPDATE = 'CHARACTER_SHEET_UPDATE';
export const CHARACTER_SHEET_UPDATE_PENDING = 'CHARACTER_SHEET_UPDATE_PENDING';
export const CHARACTER_SHEET_UPDATE_SUCCESS = 'CHARACTER_SHEET_UPDATE_SUCCESS';
export const CHARACTER_SHEET_UPDATE_FAILED = 'CHARACTER_SHEET_UPDATE_FAILED';

export const CHARACTER_SHEET_CLEAR = 'CHARACTER_SHEET_CLEAR';