export const CHARACTER_SHEET_NAME_UPDATE: string = 'CHARACTER_SHEET_NAME_UPDATE';
export const CHARACTER_SHEET_PLAYER_UPDATE: string = 'CHARACTER_SHEET_PLAYER_UPDATE';
export const CHARACTER_SHEET_CREATE: string = 'CHARACTER_SHEET_CREATE';
export const CHARACTER_SHEET_CREATE_PENDING: string = 'CHARACTER_SHEET_CREATE_PENDING';
export const CHARACTER_SHEET_CREATE_SUCCESS: string = 'CHARACTER_SHEET_CREATE_SUCCESS';
export const CHARACTER_SHEET_CREATE_FAILED: string = 'CHARACTER_SHEET_CREATE_FAILED';
export const CHARACTER_SHEET_CLEAR: string = 'CHARACTER_SHEET_CLEAR';